sudo: false
os: osx
osx_image: xcode8.2
install:
  - mkdir -p ~/bin
  - export PATH=~/bin:$PATH
  - curl -L https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh -o ~/bin/boot
  - chmod +x ~/bin/boot
cache:
  directories:
  - $HOME/.m2
  - $HOME/.boot/cache/bin
  - $HOME/.boot/cache/lib
  - $HOME/bin

script: boot inst && cd example && boot build
